### ISSUE TITLE
How to automatically add caption when image added

### ISSUE THREAD

**Issue by akshayshrivastav** [StudioJunkyard/summernote-image-captionit#5]
Hi,

I loved your implementation for caption. I would also like to know that how can i make caption automatically appear as soon as the image is loaded in summernote instead of clicking on the caption button

**Comment by DennisSuitters** [comment]
Sorry, I haven't commented sooner. I tried to implement this today, and while I was able to add a `<figure/>` and `<figcaption/>` for the image via the ImageDialog, it keeps adding everything outside of the editor, rather than in the editing area, so is something I think I need to discus with the other devs, as this happens with some other elements as well when trying to add features like this, it's like the wrapping function isn't working correctly.
